# This is the feature branch pipeline. It does not update any infrastructure, but instead
# performs sanity checks of the templates to verify that they meet minimum standards.

env:
  # Ensure all jobs use these values from the agent environment
  WEBCMS_ENVIRONMENT: ${WEBCMS_ENVIRONMENT}
  WEBCMS_SITE: ${WEBCMS_SITE}
  WEBCMS_IMAGE_TAG: ${WEBCMS_IMAGE_TAG}
  WEBCMS_REPO_URL: ${WEBCMS_REPO_URL}

steps:
  - label: ":docker: Build images"
    command: bash .buildkite/build-images.sh

    # Limit build concurrency to 1 per branch: this throttles overlapping builds
    concurrency_group: $BUILDKITE_PIPELINE_SLUG/build-$BUILDKITE_BRANCH
    concurrency: 1

    plugins:
      # Assume cross-account build role. We don't log in directly to ECR as Kaniko is able
      # to do that for us.
      - cultureamp/aws-assume-role#v0.1.0:
          role: arn:aws:iam::316981092358:role/BuildkiteRoleForImageBuilds

  # Perform a Terraform formatting check. See the terraform-fmt.sh script for more details
  # on what is executed in this step.
  - label: ":terraform: Formatting"
    plugins:
      - docker#v3.5.0:
          image: hashicorp/terraform:0.14.9
          entrypoint: /bin/sh
          command: [.buildkite/terraform-fmt.sh]

  # For feature branches, we plan three modules: network, infrastructure, and webcms. This
  # way, all branches can be evaluated for their potential impact on existing
  # infrastructure. These plans can all be executed in parallel, meaning that they should
  # have only a minimal impact on build time.

  - label: ":pipeline: :terraform: network"
    command: buildkite-agent pipeline upload .buildkite/terraform.plan.yml
    env:
      WEBCMS_SSM_NAMESPACE: /terraform/${WEBCMS_ENVIRONMENT}/network
      WEBCMS_TF_MODULE: network

  - label: ":pipeline: :terraform: infrastructure"
    command: buildkite-agent pipeline upload .buildkite/terraform.plan.yml
    env:
      WEBCMS_SSM_NAMESPACE: /terraform/${WEBCMS_ENVIRONMENT}/infrastructure
      WEBCMS_TF_MODULE: infrastructure

  # We arbitrarily choose English for a Terraform plan. The two sites' configurations
  # should not be so different that this will miss subtleties with Spanish-language
  # deployments.
  - label: ":pipeline: :terraform: webcms"
    command: buildkite-agent pipeline upload .buildkite/terraform.plan.yml
    env:
      WEBCMS_SSM_NAMESPACE: /terraform/${WEBCMS_ENVIRONMENT}/${WEBCMS_SITE}/en
      WEBCMS_TF_MODULE: webcms
      WEBCMS_LANG: en
