# This is the primary pipeline for builds. It dispatches different pipelines based on
# which branch this build is for. Feature branches only perform basic validation steps,
# whereas for the main and integration branches, we perform a full deployment.

env:
  # Common image tag used across steps
  WEBCMS_IMAGE_TAG: $BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER

  # Base URL for image repositories
  WEBCMS_REPO_URL: 316981092358.dkr.ecr.us-east-2.amazonaws.com

steps:
  # For all feature branches, only perform build & validation steps. Nothing is deployed
  # in this pipeline.
  - label: ":pipeline: Feature"
    if: build.branch != "main" && build.branch != "integration" && build.branch != "migration"

    command: buildkite-agent pipeline upload .buildkite/feature.yml
    env:
      # We specify the staging site since most feature branches target main instead
      # of integration
      WEBCMS_ENVIRONMENT: preproduction
      WEBCMS_SITE: stage

  # Steps below this line are gated by build.branch matching a specific branch, and
  # build.pull_request_id == null, which prevents Buildkite from doing deployments if the
  # targeted branch is the source in a PR. (This is a rare but observed occurrence.)
  - label: ":pipeline: Infrastructure"
    if: build.branch == "integration" && build.pull_request.id == null

    command: buildkite-agent pipeline upload .buildkite/infrastructure.yml
    env:
      WEBCMS_ENVIRONMENT: preproduction

  # As with the above wait, we have to ensure the infrastructure was successfully deployed
  # before continuing. (Note that in the case of non-main branches, the network and
  # infrastructure steps are skipped, and the waits incur no penalty.)
  - wait: ~

  # On the integration branch, we deploy the dev site
  - label: ":pipeline: Dev"
    if: build.branch == "integration" && build.pull_request.id == null

    command: buildkite-agent pipeline upload .buildkite/webcms.yml
    env:
      WEBCMS_ENVIRONMENT: preproduction
      WEBCMS_SITE: dev

  # On the main branch, we deploy the stage site
  - label: ":pipeline: Stage"
    if: build.branch == "main" && build.pull_request.id == null

    command: buildkite-agent pipeline upload .buildkite/webcms.yml
    env:
      WEBCMS_ENVIRONMENT: preproduction
      WEBCMS_SITE: stage
